---
# handlers file for tomcat
- name: "restart tomcat"
  ansible.builtin.systemd:
    name: templates/tomcat.service.j2
    state: restarted
- name: "give execute permissions to shell files"
  ansible.builtin.shell:
    cmd: "chmod +x /opt/tomcat/latest/bin/*.sh"
    executable: "/bin/bash"
